version: 2

sources:
  - name: elook_commerce
    database: ELOOK_COMMERCE
    schema: DBT_RSANJAYDESAI
    tables:
      - name: mart_users
      - name: orders
      - name: products
      - name: order_items
