version: 2

sources:
  - name: elook_commerce
    database: ELOOK_COMMERCE
    schema: RAW
    tables:
      - name: users
      - name: orders
      - name: products
      - name: order_items
